excerpt_separator: ""
highlighter: rouge
pygments: 
markdown: kramdown
url: http://mr-uuid.github.io/blog
name: First Blog
description: "My first blog!"
author: Omar Eid
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 
